services:
  keycloak.auth.api:
    image: keycloak.auth.api
    build:
      context: .
      dockerfile: Keycloak.Auth.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: Keycloak
    command: start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
    volumes:
      - ./.containers/identity:/opt/keycloak/data
    ports:
      - "18080:8080"