services:
  keycloak.auth.api:
    image: keycloak.auth.api
    build:
      context: .
      dockerfile: Keycloak.Auth.Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger:4317"
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Development"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: Keycloak
    command: start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
    volumes:
      - ./.containers/identity:/opt/keycloak/data
    ports:
      - "18080:8080"
        
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"